theme: jekyll-theme-cayman
description: "Practical ML for Developing Countries Workshop @ ICLR 2022, 
    <br/> Learning under limited/low resource scenarios.  Virtual"
basepath: "iclr2022/"
google_analytics: UA-156425047-1

navigation:
- text: HOME
  url: /
- text: CALL FOR PAPERS
  url: /cfp.html
- text: DATES
  url: /dates.html
  layout: project
- text: ORGANIZERS
  url: /organizers.html
